all:
  vars:
    ansible_password: vagrant
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: ./ssh/id_rsa
  hosts:
    k8s-master-0:
      ansible_host: 192.168.60.32
      ip: 192.168.60.32
      access_ip: 192.168.60.32
        #      node_taints:
        #        - "node.cilium.io/agent-not-ready=true:NoExecute"
    k8s-master-1:
      ansible_host: 192.168.60.33
      ip: 192.168.60.33
      access_ip: 192.168.60.33
        #      node_taints:
        #        - "node.cilium.io/agent-not-ready=true:NoExecute"
    k8s-worker-0:
      ansible_host: 192.168.60.64
      ip: 192.168.60.64
      access_ip: 192.168.60.64
        #      node_taints:
        #        - "node.cilium.io/agent-not-ready=true:NoExecute"
    k8s-worker-1:
      ansible_host: 192.168.60.65
      ip: 192.168.60.65
      access_ip: 192.168.60.65
        #      node_taints:
        #        - "node.cilium.io/agent-not-ready=true:NoExecute"
    k8s-worker-2:
      ansible_host: 192.168.60.66
      ip: 192.168.60.66
      access_ip: 192.168.60.66
        #      node_taints:
        #        - "node.cilium.io/agent-not-ready=true:NoExecute"
    k8s-worker-3:
      ansible_host: 192.168.60.67
      ip: 192.168.60.67
      access_ip: 192.168.60.67
        #      node_taints:
        #        - "node.cilium.io/agent-not-ready=true:NoExecute"
  children:
    kube_control_plane:
      hosts:
        k8s-master-0:
        k8s-master-1:
    kube_node:
      hosts:
        k8s-master-0:
        k8s-master-1:
        k8s-worker-0:
        k8s-worker-1:
        k8s-worker-2:
        k8s-worker-3:
    etcd:
      hosts:
        k8s-master-0:
        k8s-master-1:
        k8s-worker-0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
