all:
  vars:
    ansible_password: vagrant
    ansible_ssh_user: vagrant
  hosts:
    node1:
      ansible_host: 192.168.60.32
      ip: 192.168.60.32
      access_ip: 192.168.60.32
    node2:
      ansible_host: 192.168.60.33
      ip: 192.168.60.33
      access_ip: 192.168.60.33
    node3:
      ansible_host: 192.168.60.64
      ip: 192.168.60.64
      access_ip: 192.168.60.64
    node4:
      ansible_host: 192.168.60.65
      ip: 192.168.60.65
      access_ip: 192.168.60.65
    node5:
      ansible_host: 192.168.60.66
      ip: 192.168.60.66
      access_ip: 192.168.60.66
    node6:
      ansible_host: 192.168.60.67
      ip: 192.168.60.67
      access_ip: 192.168.60.67
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
