all:
  vars:
    ansible_password: vagrant
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: /src/kubespray/ssh/id_rsa
  hosts:
    k8s-master-0:
      ansible_host: 192.168.60.32
      ip: 192.168.60.32
      access_ip: 192.168.60.32
    k8s-worker-0:
      ansible_host: 192.168.60.64
      ip: 192.168.60.64
      access_ip: 192.168.60.64
  children:
    kube_control_plane:
      hosts:
        k8s-master-0:
    kube_node:
      hosts:
        k8s-master-0:
        k8s-worker-0:
    etcd:
      hosts:
        k8s-master-0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
